# Generated by Django 5.0.6 on 2024-07-13 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250, unique_for_date='created')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PB', 'Published'), ('DR', 'Draft')], max_length=2)),
                ('created', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='blog_blog_created_e5cf26_idx')],
            },
        ),
    ]
