# Generated by Django 5.0.6 on 2024-07-13 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Post',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='blog_post_created_76eb4c_idx',
            old_name='blog_blog_created_e5cf26_idx',
        ),
    ]
